apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: boutique
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: online-boutique
spec:
  description: Online Boutique DevSecOps environments (dev/staging/prod)
  sourceRepos:
    - https://github.com/Hephast0s/boutique-devsecops.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: 'boutique-*'
    - server: https://kubernetes.default.svc
      namespace: 'monitoring'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'kyverno.io'
      kind: ClusterPolicy
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
  namespaceResourceBlacklist: []
